#server:
#  port: 8081
#

#
#keycloak:
#  realm: gestion-sinistre
#  auth-server-url: http://localhost:8080
#  resource: backend
#  credentials:
#    secret: aBC8ptYUHWv4ns7MBSP7mYYRXmaIVXgF


spring:
  security:
    filter:
      dispatch:
        request: true
  main:
    allow-circular-references: true
