spring.application.name=Gestion_Sinistre
server.port=8098

# PostgreSQL DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_sinistre
spring.datasource.username=keycloak
spring.datasource.password=keycloak

# PostgreSQL JDBC driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA with PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



