version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-sql-bsn
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    restart: unless-stopped

  keycloak:
    image: bitnami/keycloak:15.0.2
    container_name: keycloak
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak_db
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloak
    ports:
      - "9090:8080"
    depends_on:
      - postgres
    networks:
      - spring-demo
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-bsn
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    networks:
      - spring-demo
    restart: unless-stopped
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres_data:
    driver: local
